version: '3.8'

services:
  gaianet:
    build: .
    container_name: gaianet
    ports:
      - "${GAIANET_API_PORT}:8080"
      - "${GAIANET_CHAT_UI_PORT}:9068"
      - "${GAIANET_CHAT_WS_PORT}:9069"
    volumes:
      - "${GAIANET_DATA_DIR}:/root"
    restart: unless-stopped
